version: '3'

services:
    postgres:
        image: postgres:15
        restart: always
        networks:
            - backend
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./app/config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
        env_file:
            - ./app/config/.env
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "devdb", "-U", "dev" ]
            timeout: 45s
            interval: 10s
            retries: 10

    app:
        build: app
        ports:
            - 3200:3200
        networks:
            - backend
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    db:

networks:
    backend:
        driver: bridge